# Generated by Django 5.0 on 2023-12-29 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emp_app', '0002_location'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Location',
        ),
    ]
